output.skip = 'Skip';
output.appName = 'Odoo Mobile App';
output.Continue = 'Continue';
output.signInKey = 'Sign In or Register';
output.signInWithEmail = 'SIGN IN WITH EMAIL';
output.createAnAccount = 'CREATE AN ACCOUNT';
output.emailKey = 'Email Address*';
output.guestEmailKey = 'Email*';
output.companyNameKey = 'Company Name*';
output.tinVat = 'TIN/VAT';
output.emailValue = 'webkul12@webkul.com';  // dynamic value
output.passwordKey = 'Password*';
output.newPasswordKey = 'New Password*';
output.confirmPasswordKey = 'Confirm Password*';
output.nameKey = 'Name*';
output.passwordValue = 'Webkul@123';  // dynamic value
output.signInBtn = 'SIGN IN';
output.LoginSuccessfully = 'Login successfully.';
output.createSuccessfully = 'Created Successfully.';
output.profile = 'Profile\nTab 4 of 4';
output.categories = 'Categories\nTab 2 of 4';
output.signOut = 'Sign Out';
output.signIn = 'Sign In';
output.ok = 'OK';
output.addToCart = 'ADD TO CART';
output.quantity = 'Quantity';
output.amtToPaid = 'Amt. to be paid';
output.emptyCart = 'EMPTY CART';
output.emptyCartMsg = 'You have no items in cart.';
output.continueShopping = 'CONTINUE SHOPPING';
output.proceed = 'PROCEED';
output.contactInformation = 'Contact Information';
output.shippingAddress = 'Shipping Address';
output.addNewAddress = 'ADD NEW ADDRESS';
output.yourName = 'Your Name*';
output.telephone = 'Telephone*';
output.streetAddress = 'Street Address*';
output.city = 'City*';
output.country = 'Country*';
output.state = 'State*';
output.zipCode = 'Zip/Postal Code*';
output.saveAddress = 'Save Address';
output.placeOrder = 'PLACE ORDER';
output.relatedProduct = 'Related Product';
output.search = 'Search by keyword and product ';
output.searchProduct = "Test Product\n$57.50"; // dynamic value
output.wishlist = "WISHLIST";
output.accountInfo = "Account Info";
output.compareProduct = "Compare Product";
output.wishlistSuccessMsg = "Item moved to Wishlist";
output.removeAllItems = "Remove All items";
output.viewAll = "View All";
output.sort = "Sort";
output.details = "DETAILS";
output.reviews = "REVIEWS";
output.placedOn = "Placed On";
output.billingAddress = "Billing Address";
output.allOrders = "All Orders";
output.sortValue = "Newest Arrivals"; // dynamic value
output.productData = "9 to 5 BB Cream\n$22.99\n1\nSale";   // dynamic value


